# Site
title:              secutron's blog
tagline:            'gray programmer'
description:        "blog for gray of deep learning and computer vision"
logo:               '/assets/img/logo.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
encoding:           utf-8
url:                https://secutron.github.io


# Site configurations
gems:
  - jekyll-paginate
markdown: kramdown
kramdown:
  input: GFM
excerpt_separator: "<!-- more -->"
sass:
  style: compressed
  sass_dir: _scss    
paginate: 5
paginate_path: '/blog/page:num'
permalink: pretty
version: 1.0.0

# About/contact
author:
  name: secutron
  description: <strong>린연</strong> fiftish gray programmer
  gravatar: 25ae2ac7a35e2cc2b3c48c1a29753c51 # md5 hash of your email address
  contact:
    linkedin:  https://www.linkedin.com/in/hyun-kim-45020325/
    github:    https://github.com/secutron
    #facebook: <hide> 
    #twitter:  <hide>
    #weibo:    <hide>
    email:     mailto:secutron@naver.com

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Contents:           
    - '/blog/'
    - { Categories: '/blog/categories/' }
    - { Tags: '/blog/tags/' }
  About:          
    - '/about/'

# Where are tags and categories displayed
tag_page: '/blog/tags/'
category_page: '/blog/categories/'

hero:
  image: https://secutron.github.io/assets/img/baby.jpg
  caption: Action/Activity for baby caring

# plugin
mathjax: true # whether support mathjax
google_analytics_token: 'UA-125587105-1' # leave blank if you don't want google analytics
disqus_shortname:   'secutron'
